/**
 * Convert LaTeX math to HTML with MathML-like structure
 * This is a simplified conversion for demo purposes
 * In production, CKEditor will handle this automatically
 */
export function latexToHtml(text: string): string {
  // For demo purposes, we'll wrap math in special spans
  // CKEditor with MathType will produce proper MathML

  // Handle display math $$...$$
  text = text.replace(/\$\$(.*?)\$\$/gs, (match, math) => {
    return `<span class="math-display" style="display: block; text-align: center; margin: 10px 0;">
      <math xmlns="http://www.w3.org/1998/Math/MathML">
        <mtext>${math}</mtext>
      </math>
    </span>`;
  });

  // Handle inline math $...$
  text = text.replace(/\$(.*?)\$/g, (match, math) => {
    return `<span class="math-inline">
      <math xmlns="http://www.w3.org/1998/Math/MathML">
        <mtext>${math}</mtext>
      </math>
    </span>`;
  });

  // Convert markdown formatting
  text = text.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
  text = text.replace(/\n/g, '<br>');

  return text;
}

/**
 * Sample HTML content that would be generated by CKEditor
 */
export const sampleHtmlContent = {
  // Example of a math equation
  quadraticEquation: `<p>Giải phương trình: <math xmlns="http://www.w3.org/1998/Math/MathML"><msup><mi>x</mi><mn>2</mn></msup><mo>-</mo><mn>5</mn><mi>x</mi><mo>+</mo><mn>6</mn><mo>=</mo><mn>0</mn></math></p>`,

  // Example of a set notation
  setNotation: `<p>Cho tập hợp <math xmlns="http://www.w3.org/1998/Math/MathML"><mi>A</mi><mo>=</mo><mo>{</mo><mn>1</mn><mo>,</mo><mn>2</mn><mo>,</mo><mn>3</mn><mo>,</mo><mn>4</mn><mo>,</mo><mn>5</mn><mo>}</mo></math> và <math xmlns="http://www.w3.org/1998/Math/MathML"><mi>B</mi><mo>=</mo><mo>{</mo><mn>3</mn><mo>,</mo><mn>4</mn><mo>,</mo><mn>5</mn><mo>,</mo><mn>6</mn><mo>,</mo><mn>7</mn><mo>}</mo></math>. Tìm <math xmlns="http://www.w3.org/1998/Math/MathML"><mi>A</mi><mo>∩</mo><mi>B</mi></math></p>`,

  // Example of a fraction
  fraction: `<p><math xmlns="http://www.w3.org/1998/Math/MathML"><mfrac><mrow><mi>x</mi><mo>+</mo><mn>1</mn></mrow><mrow><mi>x</mi><mo>-</mo><mn>1</mn></mrow></mfrac></math></p>`,

  // Example of square root
  squareRoot: `<p><math xmlns="http://www.w3.org/1998/Math/MathML"><msqrt><msup><mi>x</mi><mn>2</mn></msup><mo>+</mo><msup><mi>y</mi><mn>2</mn></msup></msqrt></math></p>`,

  // Example of integral
  integral: `<p><math xmlns="http://www.w3.org/1998/Math/MathML"><msubsup><mo>∫</mo><mn>0</mn><mn>1</mn></msubsup><msup><mi>x</mi><mn>2</mn></msup><mi>dx</mi></math></p>`
};